<?php

namespace App\Console\Commands;

use App\Services\ControlPlane\Connectors\Support\Platform;
use Illuminate\Console\Command;
use Illuminate\Support\Str;

/**
 * Phase 27M.3 — scaffold a safe connector skeleton. The generated package
 * is trust=unverified: it is NOT auto-enabled and must be explicitly
 * promoted by the operator (config connectors.enabled_trust_levels or code
 * change) after review. No arbitrary code is ever auto-registered trusted.
 */
class ConnectorMakeCommand extends Command
{
    protected $signature = 'connector:make {name : Connector name, e.g. demo-source or DemoSource}';

    protected $description = 'Scaffold a new source connector package (unverified trust, disabled by default)';

    public function handle(): int
    {
        $input = (string) $this->argument('name');
        $key = Str::kebab(str_replace(['_', '.'], '-', $input));
        $key = strtolower($key);
        if (! preg_match('/^[a-z][a-z0-9]{1,20}(-[a-z0-9]{1,20}){0,4}$/', $key)) {
            $this->error("Connector key '{$key}' is invalid — use lowercase kebab, max 32 chars.");

            return self::FAILURE;
        }
        $classBase = Str::studly($key);
        $dir = app_path('Connectors/'.$classBase);
        if (is_dir($dir)) {
            $this->error("Package directory already exists: {$dir}");

            return self::FAILURE;
        }

        $namespace = 'App\\Connectors\\'.$classBase;
        if (! @mkdir($dir, 0777, true) && ! is_dir($dir)) {
            $this->error("Could not create {$dir}");

            return self::FAILURE;
        }

        $replacements = [
            '{{KEY}}' => $key,
            '{{CLASS}}' => $classBase.'Connector',
            '{{CLASS_BASE}}' => $classBase,
            '{{NAMESPACE}}' => $namespace,
            '{{VERSION}}' => '0.1.0',
            '{{DATE}}' => now()->toDateString(),
        ];
        $fill = fn (string $template) => strtr($template, $replacements);

        file_put_contents($dir.'/connector.json', json_encode([
            'schema_version' => 1,
            'key' => $key,
            'name' => $classBase,
            'version' => '0.1.0',
            'description' => $classBase.' source connector (scaffolded '.now()->toDateString().').',
            'author' => (string) config('platform.name'),
            'license' => 'MIT',
            'platform_requirement' => '>='.Platform::core(),
            'entrypoint' => $namespace.'\\'.$classBase.'Connector',
            'capabilities' => ['database_metadata', 'data_extraction', 'read_only_enforcement', 'source_fingerprint'],
            'permissions' => ['filesystem.dataset.read'],
            'trust' => 'unverified',
            'import_flow' => 'credentials-form',
            'category' => 'source',
            'ui' => [
                'display_name' => $classBase,
                'icon' => 'heroicon-o-link',
                'docs_url' => null,
                'setup_instructions' => 'Configure the connector credential fields, test the connection, then analyze.',
            ],
        ], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));

        $classTemplate = <<<'PHP'
<?php

namespace {{NAMESPACE}};

use App\Models\MigrationSource;
use App\Models\Project;
use App\Services\ControlPlane\Connectors\ConnectorCapability;
use App\Services\ControlPlane\Connectors\ConnectorCredentialField;
use App\Services\ControlPlane\Connectors\ConnectorCredentials;
use App\Services\ControlPlane\Connectors\ConnectorDefinition;
use App\Services\ControlPlane\Connectors\ConnectorHealth;
use App\Services\ControlPlane\Connectors\ConnectorManifest;
use App\Services\ControlPlane\Connectors\ConnectorTestResult;
use App\Services\ControlPlane\Connectors\Contracts\SourceConnector;
use App\Services\ControlPlane\Connectors\Support\BaseSourceAdapter;
use App\Services\ControlPlane\Migration\Contracts\SourceAdapter;

/**
 * Scaffolded source connector ({{KEY}}) — {{DATE}}.
 *
 * Generated by `php artisan connector:make`. Registered as trust=unverified:
 * it stays DISABLED until an operator explicitly enables it after review.
 * Implement the TODOs, then run `php artisan connector:test {{KEY}}`.
 */
class {{CLASS}} implements SourceConnector
{
    private ?ConnectorManifest $manifest = null;
    private ?ConnectorDefinition $definition = null;

    public function manifest(): ConnectorManifest
    {
        return $this->manifest ??= ConnectorManifest::parseFile(__DIR__.DIRECTORY_SEPARATOR.'connector.json');
    }

    public function definition(): ConnectorDefinition
    {
        if ($this->definition !== null) {
            return $this->definition;
        }

        // TODO: declare the credential/configuration fields this connector needs.
        $credentials = [];
        $configuration = [
            new ConnectorCredentialField(
                key: 'source_location',
                label: 'Source location',
                type: 'text',
                required: true,
                scope: ConnectorCredentialField::SCOPE_CONFIGURATION,
                help: 'Describe where the source data lives.',
                capability: ConnectorCapability::DATABASE_METADATA,
            ),
        ];

        return $this->definition = ConnectorDefinition::fromManifest($this->manifest(), $credentials, $configuration);
    }

    public function credentialSchema(): array
    {
        return array_merge($this->definition()->credentials, $this->definition()->configuration);
    }

    public function capabilities(): array
    {
        return $this->manifest()->capabilities();
    }

    public function capabilityStatus(string $capability, array $resolvableFieldKeys = []): string
    {
        if (! in_array($capability, $this->capabilities(), true)) {
            return ConnectorCapability::NOT_SUPPORTED;
        }

        return in_array('source_location', $resolvableFieldKeys, true)
            ? ConnectorCapability::SUPPORTED
            : ConnectorCapability::SUPPORTED_WITH_CONFIGURATION;
    }

    public function testConnection(ConnectorCredentials $credentials): ConnectorTestResult
    {
        // TODO: attempt a read-only connection with the given (scoped)
        // credentials and classify the outcome honestly.
        if (! $credentials->has('source_location')) {
            return ConnectorTestResult::make(ConnectorTestResult::INVALID_CONFIGURATION, 'source_location is required.');
        }

        return ConnectorTestResult::make(ConnectorTestResult::UNKNOWN_ERROR, 'Not implemented — scaffold only.');
    }

    public function health(MigrationSource $source): ConnectorHealth
    {
        return ConnectorHealth::make($source->status === 'ready' ? ConnectorHealth::CONNECTED : ConnectorHealth::DISCONNECTED, 'source status: '.$source->status);
    }

    public function discoverProjects(ConnectorCredentials $credentials): array
    {
        return [];
    }

    public function createSourceProfile(Project $project, array $selection, array $configuration, ?int $environmentId = null): MigrationSource
    {
        return MigrationSource::create([
            'project_id' => $project->id,
            'environment_id' => $environmentId,
            'type' => self::key(),
            'display_name' => $configuration['display_name'] ?? '{{CLASS_BASE}} source',
            'connection' => array_filter([
                'source_location' => $configuration['source_location'] ?? null,
            ]),
            'secret_refs' => [],
            'read_only' => true,
            'status' => 'pending',
            'created_by' => auth()->id(),
        ]);
    }

    public static function key(): string
    {
        return '{{KEY}}';
    }

    public function sourceAdapter(MigrationSource $source): SourceAdapter
    {
        return new class($source) extends BaseSourceAdapter
        {
            public function connect(): void
            {
                throw new \LogicException('TODO: implement the read-only connection for this connector.');
            }

            public function inventory(): array
            {
                throw new \LogicException('TODO: return the normalized inventory (27B.2 shape).');
            }

            public function countRows(string $schema, string $table): int
            {
                throw new \LogicException('TODO: implement row counting.');
            }

            public function streamRows(string $schema, string $table, array $columns, callable $callback, int $batchSize = 500): int
            {
                throw new \LogicException('TODO: implement batched read-only extraction.');
            }
        };
    }

    public function analyze(MigrationSource $source): array
    {
        return $this->sourceAdapter($source)->inventory();
    }

    public function extract(MigrationSource $source, string $schema, string $table, array $columns, callable $callback, int $batchSize = 500): int
    {
        return $this->sourceAdapter($source)->streamRows($schema, $table, $columns, $callback, $batchSize);
    }

    public function validateSource(MigrationSource $source): array
    {
        return ['kind' => 'connector_validation', 'connector_key' => $this->manifest()->key(), 'note' => 'TODO: provide validation artifacts'];
    }

    public function fingerprint(MigrationSource $source): string
    {
        return $this->sourceAdapter($source)->fingerprint();
    }
}
PHP;
        file_put_contents($dir.'/'.$classBase.'Connector.php', $fill($classTemplate));

        $readmeTemplate = <<<'MD'
# {{KEY}} connector

Scaffolded {{DATE}} by `php artisan connector:make {{KEY}}`.

## Status

- Trust level: `unverified` — the package is **disabled by default** and
  will not register as enabled until an operator promotes it (27K.1).
- Phase 27J.4: there is no remote marketplace; packages are local, reviewed,
  operator-installed code.

## Next steps

1. Implement `testConnection`, the source adapter (`connect`, `inventory`,
   `countRows`, `streamRows`) and `validateSource` in `{{CLASS}}.php`.
2. Adjust the credential schema and `connector.json` manifest.
3. Run the contract battery: `php artisan connector:test {{KEY}}`
4. Inspect the definition: `php artisan connector:inspect {{KEY}}`
5. After review, enable by adding your trust level to
   `CONNECTOR_ENABLED_TRUST_LEVELS` / `config/connectors.php`.

See docs/connectors/CONNECTOR_DEVELOPMENT.md and BUILD_YOUR_FIRST_CONNECTOR.md.
MD;
        file_put_contents($dir.'/README.md', $fill($readmeTemplate));

        file_put_contents($dir.'/.gitignore', "datasets/\n");

        $this->info("Scaffolded connector package: {$dir}");
        $this->line('  connector.json           — manifest (trust: unverified, disabled by default)');
        $this->line('  '.$classBase.'Connector.php — connector + adapter skeleton (TODOs marked)');
        $this->line('  README.md                — package notes');
        $this->line('');
        $this->line('Next: implement the TODOs, then `php artisan connector:test '.$key.'`.');

        return self::SUCCESS;
    }
}
