<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class AdminAuditEntry extends Model
{
    public const ACTIONS = [
        'USER_CREATED', 'USER_UPDATED', 'USER_DISABLED', 'USER_ENABLED',
        'USER_PASSWORD_RESET_SENT', 'TOKEN_REVOKED', 'SESSION_REVOKED',
        'ROLE_CREATED', 'ROLE_UPDATED', 'ROLE_DELETED',
        'PERMISSION_CREATED', 'PERMISSION_UPDATED', 'PERMISSION_DELETED',
        'RECORD_CREATED', 'RECORD_UPDATED', 'RECORD_DELETED',
        'BACKUP_TRIGGERED', 'BACKUP_VERIFIED',
        'QUEUE_JOB_RETRIED', 'QUEUE_JOB_DELETED', 'QUEUE_WORKERS_RESTARTED',
        'PROJECT_MAINTENANCE_ENABLED', 'PROJECT_MAINTENANCE_DISABLED',
        'PROJECT_CACHE_CLEARED', 'PROJECT_HEALTH_CHECKED', 'SCHEDULER_RUN',
        'STORAGE_FILE_UPLOADED', 'STORAGE_FILE_DELETED', 'STORAGE_FILE_MOVED', 'STORAGE_FILE_DOWNLOADED',
        'STORAGE_BUCKET_CREATED', 'STORAGE_BUCKET_DELETED',
        'PROJECT_SETTINGS_UPDATED',
        // Phase 20 platform surfaces.
        'SQL_READ_EXECUTED', 'SQL_WRITE_EXECUTED', 'SQL_BLOCKED',
        'WRITE_MODE_ENABLED', 'WRITE_MODE_EXPIRED',
        'TABLE_CREATED', 'TABLE_ALTERED', 'TABLE_DROPPED',
        'COLUMN_ADDED', 'FK_CREATED', 'FK_DROPPED',
        'DB_FUNCTION_CREATED', 'DB_FUNCTION_TESTED', 'DB_FUNCTION_DELETED',
        'FUNCTION_CREATED', 'FUNCTION_DEPLOYED', 'FUNCTION_INVOKED', 'FUNCTION_ROLLED_BACK', 'FUNCTION_DELETED',
        'APIKEY_CREATED', 'APIKEY_REVOKED', 'APIKEY_ROTATED',
        'SECRET_CREATED', 'SECRET_ROTATED', 'SECRET_DELETED',
        'WEBHOOK_CREATED', 'WEBHOOK_UPDATED', 'WEBHOOK_DELETED', 'WEBHOOK_DELIVERED',
        'TASK_CREATED', 'TASK_UPDATED', 'TASK_RUN', 'TASK_DISABLED',
        'MIGRATION_RUN', 'MIGRATION_ROLLED_BACK',
        'BACKUP_RESTORED_LOCAL', 'CREDENTIALS_ROTATED',
        'TEAM_ROLE_ASSIGNED', 'CONNECTION_SNAPSHOT_REFRESHED',
        'RECORDS_EXPORTED', 'RECORDS_IMPORTED',
        'API_SNAPSHOT_REFRESHED',
        // Phase 21 multi-node surfaces.
        'NODE_TOKEN_ROTATED', 'PROJECT_ENDPOINT_UPDATED', 'PROJECT_PROFILE_UPDATED',
        // Phase 24 productization surfaces.
        'MIGRATION_SOURCE_CREATED', 'MIGRATION_SOURCE_UPDATED', 'MIGRATION_SOURCE_DELETED',
        'MIGRATION_ANALYSIS_RUN', 'MIGRATION_PLAN_CREATED', 'MIGRATION_PLAN_UPDATED',
        'MIGRATION_RUN_STARTED', 'MIGRATION_RUN_COMPLETED', 'MIGRATION_RUN_FAILED', 'MIGRATION_RUN_CANCELLED',
        'MIGRATION_VALIDATED', 'CLEAN_REHEARSAL_RUN',
        'ENVIRONMENT_CREATED', 'ENVIRONMENT_UPDATED', 'ENVIRONMENT_SWITCHED', 'PROMOTION_ATTEMPTED',
        'SECRET_REVEALED',
        'BACKUP_POLICY_CREATED', 'BACKUP_POLICY_UPDATED', 'BACKUP_DESTINATION_CREATED',
        'RESTORE_DRILL_REQUESTED', 'RESTORE_DRILL_PASSED', 'RESTORE_DRILL_FAILED',
        'SCHEMA_SNAPSHOT_CREATED', 'SCHEMA_DIFF_RUN', 'DRIFT_ACKNOWLEDGED',
        'READINESS_ACKNOWLEDGED', 'READINESS_SNAPSHOT_RECORDED',
        'RESOURCE_THRESHOLD_UPDATED', 'COST_ENTRY_UPDATED',
        'CLIENT_CONNECTION_TESTED',
        'ONBOARDING_STARTED', 'ONBOARDING_COMPLETED',
        // Phase 25 AI migration surfaces.
        'SUPABASE_ACCOUNT_CONNECTED', 'SUPABASE_ACCOUNT_DELETED', 'SUPABASE_PROJECT_SELECTED', 'SUPABASE_CONNECTION_TESTED',
        'SOURCE_CREDENTIAL_CHANGED', 'REPOSITORY_LINKED', 'CLIENT_SCAN_RUN',
        'COPILOT_RUN', 'AI_PROVIDER_SAVED', 'AI_PROVIDER_TESTED', 'AI_PROVIDER_DELETED',
        'PATCH_GENERATED', 'PATCH_APPROVED', 'PATCH_REJECTED', 'PATCH_APPLIED',
        'TEST_RUN', 'REHEARSAL_INITIATED', 'REPAIR_LOOP_RUN',
        // Phase 26 first-run setup surfaces.
        'PLATFORM_SETUP_COMPLETED',
        // Phase 27 connector/plugin surfaces.
        'CONNECTOR_PACKAGE_REJECTED', 'CONNECTOR_INSTANCE_DISABLED', 'CONNECTOR_INSTANCE_REMOVED',
        'CONNECTOR_CONNECTION_TESTED', 'CONNECTOR_CAPABILITY_PROBED', 'CONNECTOR_LIFECYCLE_EVENT',
        // Phase 32/33 — CDC + AI client conversion surfaces.
        'CUTOVER_EVENT', 'CDC_CHECKPOINT_STORED', 'CDC_CHECKPOINT_REFUSED',
        'CLIENT_CONVERSION_GENERATED', 'CLIENT_CONVERSION_TEST_REFUSED',
        // 0.4.0-rc.5 (Phase 41) — AI settings + New Project wizard.
        'AI_ENABLED_TOGGLED', 'WIZARD_SOURCE_CONNECTED', 'WIZARD_MIGRATION_STARTED',
        // 0.6.0 Phase E — workspaces created inline from the New Project wizard.
        'WORKSPACE_CREATED',
        // 0.4.0 — Nexus Copilot (mission §30). Every meaningful AI action is
        // recorded, and an AI action must be distinguishable from a human one
        // (the metadata carries `actor_kind = ai`).
        'AI_CONVERSATION_TURN',
        'AI_INSPECT_CONTEXT_ATTACHED',
        'AI_ACTION_PROPOSED', 'AI_ACTION_APPROVED', 'AI_ACTION_REJECTED',
        'AI_ACTION_APPLIED', 'AI_ACTION_VERIFIED',
        // Phase 43 — Developer Agent runtime surfaces. Command/file activity
        // during a task lives in agent_task_events (bounded telemetry); the
        // ADMIN ledger records lifecycle decisions and source-impacting acts.
        'AGENT_RUNTIME_CREATED', 'AGENT_RUNTIME_UPDATED', 'AGENT_RUNTIME_TESTED', 'AGENT_RUNTIME_DELETED',
        'AGENT_TASK_CREATED', 'AGENT_TASK_CANCELLED', 'AGENT_TASK_FAILED',
        'AGENT_CHANGESET_GENERATED',
        'AGENT_APPROVAL_GRANTED', 'AGENT_APPROVAL_REJECTED',
        'AGENT_APPLY_FAILED', 'AGENT_CHANGESET_APPLIED', 'AGENT_FILE_APPLIED',
        'AGENT_VERIFICATION_RECORDED',
    ];

    protected $fillable = [
        'owner_user_id', 'project_id', 'project_slug', 'action',
        'target_type', 'target_id', 'ip', 'metadata',
    ];

    protected function casts(): array
    {
        return ['metadata' => 'array'];
    }

    public function owner(): BelongsTo
    {
        return $this->belongsTo(User::class, 'owner_user_id');
    }

    public function project(): BelongsTo
    {
        return $this->belongsTo(Project::class);
    }
}
